### ISSUE TITLE
support bower install?

### ISSUE THREAD

**Issue by microlv** [ggendre/GALocalStorage#25]
Hi, could you register a package like 'ga-localstorage' in bower? so that I can easily install it by bower.

**Comment by ggendre** [comment]
Hi
That's a good idea ! I'm in the rush right now but feel free to create it yourself, I will accept any PR you may need for that purpose in less than a 24h, I promise ;)

cheers

**Comment by microlv** [comment]
Great! 
I register bower package before, but I don't have any idea about how to help another repository register it.
I have a try. :)

**Comment by microlv** [comment]
I have create a bower package, name: ga-localstorage.
you should can install by bower now.

**Comment by microlv** [comment]
support bower is done. close issue.
