### ISSUE TITLE
How to use it with angular js?

### ISSUE THREAD

**Issue by kingkarki** [ggendre/GALocalStorage#28]
I m using ionic framework. Can i use it like 
ga_storage._trackPageview('/index', 'optional title');
or i have to use it like 
$window.ga_storage._trackPageview('/index', 'optional title');

**Comment by ggendre** [comment]
Both will work. `$window` is just [a reference to the window object](https://docs.angularjs.org/api/ng/service/$window)

If you want to realy use it "the angular way" you should do a small [Service or Factory](https://docs.angularjs.org/guide/services) around ga_storage.
